#!/bin/bash
# shellcheck disable=SC1090,SC1091,SC2010,SC2016,SC2046,SC2086,SC2174
################
# Setup Script #
################
DEBIAN_FRONTEND=noninteractive timedatectl set-timezone Asia/Jakarta # setup timedate locale
sed -i "s/# net.ipv6.conf.all.disable_ipv6/net.ipv6.conf.all.disable_ipv6/g" /etc/sysctl.conf
sed -i "s/ENABLED=true/ENABLED=false/g" /etc/default/armbian-zram-config # disable zram
sed -i "s/ENABLED=true/ENABLED=false/g" /etc/default/armbian-ramlog # disable zram
sed -i "s/deb.debian.org/mr.heru.id/g" /etc/apt/sources.list # change repository debian
sed -i "s/apt.armbian.com/mirrors.aliyun.com\/armbian/g" /etc/apt/sources.list.d/armbian.list # change repository armbian
DEBIAN_FRONTEND=noninteractive systemctl disable --now wpa_supplicant.service vnstat.service # disable zram 
DEBIAN_FRONTEND=noninteractive sudo apt --purge -y remove vnstat
DEBIAN_FRONTEND=noninteractive wget https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install
DEBIAN_FRONTEND=noninteractive chmod +x ./install
DEBIAN_FRONTEND=noninteractive version=6 sudo ./install -n
sed -i "s/httpredir.debian.org/mr.heru.id/g" /etc/apt/sources.list.d/openmediavault-kernel-backports.list
DEBIAN_FRONTEND=noninteractive sudo apt clean all
DEBIAN_FRONTEND=noninteractive sudo apt -y autoremove
DEBIAN_FRONTEND=noninteractive sudo apt -y update
DEBIAN_FRONTEND=noninteractive sudo apt -y install linux-headers-generic
DEBIAN_FRONTEND=noninteractive sudo apt -y install docker podman curl wget
nmcli radio wifi off # force disable wifi
